sudo: required
dist: trusty

branches:
  only:
      - /.*/

matrix:
  include:
    - language: java
      jdk: oraclejdk8
      script:
        - ./mvnw test -B -q
      before_script:
        - cd ./webtests2-back/
        - chmod +x mvnw